name: Deploy Standalone via FTP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy standalone folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PROD_FTP_HOST }}
          username: ${{ secrets.PROD_FTP_USER }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          protocol: ftps
          local-dir: standalone/
          server-dir: ${{ secrets.PROD_ROOT_PATH }}/
          dangerous-clean-slate: false
